mod db
mod docker
_default:
    just --list

migrate:
    envx run sqlx migrate run
    just prepare

# Generate sqlx offline query data for building without a live database
prepare:
    envx run cargo sqlx prepare

build:
    envx run cargo build --release

run:
    envx run cargo run

dev:
    envx run cargo watch -x run -i "openapi.json"

spec:
    envx run cargo run -- --generate-spec
